# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammed Sharafath Abdul Hameed
title: Research Scientist
email: sharafath (at) outlook (dot) com
github: https://github.com/shara27

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  shara27
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mohammed-sharafath-abdul-hameed
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-1792-7748
# research_gate_username: Mohammed-Sharafath-Abdul-Hameed

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
  
- title: another link
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Mohammed-Sharafath-Abdul-Hameed
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Greetings! I'm Mohammed Sharafath, a Ph.D. candidate in machine learning, passionate about harnessing the potential of data to shape a brighter future.
  My journey as a research scientist has led me to develop Python packages, innovative algorithms, and custom solutions for industry partners.
  With a background in leading teams and mentoring, I've honed my problem-solving and leadership skills.
  My career has been a dynamic mix of academia and industry, equipping me with the expertise to tackle complex challenges and make a meaningful impact.
  Welcome to my portfolio!
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Bearing Failure Analysis
        description: | # this will include new lines to allow paragraphs
          The project focuses on revolutionizing predictive maintenance in industrial machinery by harnessing the power of neural networks to predict bearing failures using accelerometer vibration data.
          To address the practical issues related to the collected data, I implemented advanced signal processing techniques to filter out noise, optimized sensor positioning for accurate readings, and developed a robust predictive algorithm.
          By employing advanced machine learning techniques, this innovative endeavor aims to analyze subtle changes in vibration patterns, detecting early signs of impending bearing issues. By doing so, it enables proactive maintenance interventions, preventing costly downtime and equipment damage.
          The fully connected neural network models are designed to continuously learn and adapt, enhancing prediction accuracy over time. This project not only improves operational efficiency but also extends the lifespan of critical machinery, resulting in significant cost savings for industries reliant on heavy equipment.
      
      - layout: top-middle
        title: Health Prediction using EHR data
        additional_links:
          - title:  Publication Link
            icon: fab fa-researchgate
            url: https://www.researchgate.net/publication/357768010_Disease_Prediction_Based_on_Individual's_Medical_History_Using_CNN
        description: | # this will include new lines to allow paragraphs
          This project focuses on harnessing the potential of real-life ICD-coded Electronic Medical Records (EMR) collected in Africa between 2018-2019 to revolutionize healthcare diagnostics. Using cutting-edge machine learning techniques, particularly Convolutional Neural Networks (CNN), this research has crafted a predictive model with the aim of averting future health complications.
          The process involves transforming millions of raw EMR data points into multi-step time-series forecasting data, enabling the CNN model to accurately forecast an individual's disease risk based on their medical history and demographics.
          The biggest challenge was cleaning up the data and creating the multi-step time-series forecasting data. After training, the model impressively achieves an 80.73% accuracy rate in predicting future disease risk, promising significant cost savings, enhanced hospital capacity planning, and invaluable peace of mind regarding personal health.
      
      - layout: top-middle
        title: Gradient Monitored Reinforcement Learning
        link: github.com/shara27/personal_portfolio/tree/main/gradient_monitoring
        link_text: Project Website
        additional_links:
          - title:  Publication Link
            icon: fab fa-researchgate
            url: researchgate.net/profile/Mohammed-Sharafath-Abdul-Hameed/publication/341617567_Gradient_Monitored_Reinforcement_Learning/links/5ecba67f458515626cca43c6/Gradient-Monitored-Reinforcement-Learning.pdf
        quote: >
          An algorithmic plug-in that can be used on top of any gradient-based learning system.
        description: | # this will include new lines to allow paragraphs
          In this project, I tackled the practical challenges plaguing deep reinforcement learning (RL) or any continual learning task, by introducing a groundbreaking technique called Gradient Monitoring (GM). The primary hurdle we faced in RL was the slow convergence and poor generalization of neural networks. GM addresses this issue by meticulously curbing gradient variance, resulting in a more efficient and effective learning process.
          I didn't stop at GM; I further improved the initial algorithm and devised several variants to optimize model performance. Momentum with GM (M-WGM) allowed me to fine-tune the backpropagated gradients continuously. The Adaptive M-WGM (AM-WGM) method further refined my approach by dynamically balancing focused and distributed learning, adapting to the feedback from rewards collected during training. This innovation even facilitated automatic network size adjustment by freezing trained weights.
          Comprehensive testing on real-world multi-robot coordination problems, Atari games, and continuous control tasks using A2C and PPO revealed impressive results, highlighting the superior generalization capabilities of these methods. With GM, the way for more efficient and effective deep RL training is paved.
      
      - layout: top-middle
        title: Gym Environments for Reinforcement Learning
        link: github.com/shara27/personal_portfolio/tree/main/gym_environments
        link_text: Project Website
        quote: >
          A subset of the collections of custom Gym environments that I developed during my Ph.D.
        description: | # this will include new lines to allow paragraphs
          In reinforcement learning, having a stable environment that an agent can learn from is a crucial part of the research.
          Over the course of my research work, I developed a few environments for both robotics and digital twin applications.
          Granted, this is not the complete list as the major ones were developed for companies, which I cannot publish here. 
          But, I think this showcases my capabilities to develop usable code from complex ideas in physics, operations research, and robotics.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Promotionskolleg NRW
        caption: 2019 - 2023
        sub_title: Ph.D.
        quote: >
          The Promotionskolleg NRW (PK NRW) bundles the scientific competencies of the universities of applied sciences in North Rhine-Westphalia and offers young scientists an excellent environment for academic qualification.
        description: | # this will include new lines to allow paragraphs
          During my time at PK NRW I learnt most of the key skills that I such as leadership, teamwork, and working to tight deadlines.
          I thoroughly enjoyed my time conducting research, exploring new avenues for improvement, and in general about the need for positive collaboration with researchers from a variety of other domains.
      - layout: left
        title: FH Suedwestfalen
        caption: 2016 - 2019
        sub_title: MSc Systems Engineering and Engineering Management
        quote: >
          The FH Suedwestfalen looks back on a long history - its historically oldest predecessor was founded in 1824. It has existed in its current form since 2002 through the merger of the Maerkische Fachhochschule with the Meschede and Soest departments of the Gesamthochschule Paderborn.
        description: | # this will include new lines to allow paragraphs
          The master's was my gateway into machine learning after working in the manufacturing industry for 5 years. Doing a master's after being in the industry for so long was a difficult choice. But I do not regret choosing to do it in the slightest.
          I learnt about a lot of exciting new technologies in production systems, control systems, and of course, also machine learning. 
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning and data science some of my other interests and hobbies are:
      - Motorbikes
      - Books
      - Football
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
